### ISSUE TITLE
"NoClassDefFound Error" when building model

### ISSUE THREAD

**Issue by lhausmann** [jodaiber/model-quickstarter#3]
Hey there,
I'm trying to build a model in local mode using the index_db.sh script, but after building pig 0.14.0 the process aborts with this output.

```
copyh1Dependencies:
     [copy] Copying 1 file to /media/hdd160/model-quickstarter/wdir/pig/pig-0.14.0-src
     [move] Moving 1 file to /media/hdd160/model-quickstarter/wdir/pig/pig-0.14.0-src/legacy

copyh2Dependencies:

BUILD SUCCESSFUL
Total time: 19 seconds
######################################################################## 100.0%
Moving stopwords into HDFS...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
        at org.apache.pig.Main.<clinit>(Main.java:106)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 1 more
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/LocalFileSystem
        at org.apache.pig.Main$1.run(Main.java:101)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.LocalFileSystem
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 1 more
Could not find the main class: org.apache.pig.Main.  Program will exit.
```

I tried using Java 6, 7 and 8, but it doesn't seem to make a difference. Any idea what else I can do?

**Comment by jodaiber** [comment]
Hey!

this branch is a bit behind the main [spotlight branch](https://github.com/dbpedia-spotlight/model-quickstarter), have you tried with that one?

Jo

**Comment by lhausmann** [comment]
Hey,
that's the one I used actually, but for some reason I can't report any
issues for that one.
Am 24.04.2015 23:54 schrieb "Jo Daiber" notifications@github.com:

**Comment by jodaiber** [comment]
Ah, good to know. I added the Issues section there.

**Comment by jodaiber** [comment]
Where does the Pig 0.14 come from? Looking at `index_db.sh`, it should be using 0.10, no?

**Comment by lhausmann** [comment]
The link to the 0.10.1 version in the script is dead, 0.14.0 is the only
one available.

**Comment by jodaiber** [comment]
You're right, I thought this would have been fixed already. I updated the pig URL in the index_db.sh, please try again with that version.

**Comment by lhausmann** [comment]
Had to increase the heap size via _JAVA_OPTIONS, but it works now. Thanks!
